export const AUTH = "AUTH";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const SET_REG_ERROR_MESSAGE = "SET_REG_ERROR_MESSAGE";

export const CLEAR_USER_ERROR_MESSAGE = "CLEAR_USER_ERROR_MESSAGE";
export const SET_USER_ERROR_MESSAGE = "SET_USER_ERROR_MESSAGE";

export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILURE = "GET_USER_INFO_FAILURE";

export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAILURE = "CREATE_TRANSACTION_FAILURE";

export const GET_USER_TRANSACTIONS = "GET_USER_TRANSACTIONS";
export const GET_USER_TRANSACTIONS_SUCCESS = "GET_USER_TRANSACTIONS_SUCCESS";
export const GET_USER_TRANSACTIONS_FAILURE = "GET_USER_TRANSACTIONS_FAILURE";
export const CLEAR_GET_USER_TRANSACTIONS_ERROR_MESSAGE = "CLEAR_GET_USER_TRANSACTIONS_ERROR_MESSAGE";

export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_FAILURE = "GET_USER_LIST_FAILURE";
export const CLEAR_GET_USER_LIST_ERROR_MESSAGE = "CLEAR_GET_USER_LIST_ERROR_MESSAGE";
